services:
  sender:
    build:
      context: .
      dockerfile: sender/Dockerfile.sender
    container_name: simurf_sender
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - simurf_net

  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile.receiver
    container_name: simurf_receiver
    ports:
      - "6000:6000/udp"
    volumes:
      - simurf_logs:/logs
    networks:
      - simurf_net

  analyzer:
    build:
      context: .
      dockerfile: analyzer/Dockerfile.analyzer
    container_name: simurf_analyzer
    ports:
      - "8080:8080"
    volumes:
      - simurf_logs:/logs
    networks:
      - simurf_net

volumes:
  simurf_logs:

networks:
  simurf_net:
    driver: bridge
