services:
  sender:
    build:
      context: .
      dockerfile: sender/Dockerfile.sender
    container_name: simurf_sender
    depends_on:
      - receiver
    networks:
      - simurf_net
    # Add extra_hosts so sender can reach host's simulator
    extra_hosts:
      - "host.docker.internal:host-gateway"

  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile.receiver
    container_name: simurf_receiver
    ports:
      - "5001:5000/udp"  # Host:Container
    networks:
      - simurf_net
    # Ensure output isn't buffered
    environment:
      - PYTHONUNBUFFERED=1

  analyzer:
    build:
      context: .
      dockerfile: analyzer/Dockerfile.analyzer
    container_name: simurf_analyzer
    ports:
      - "7001:7000/udp"
    networks:
      - simurf_net
    environment:
      - PYTHONUNBUFFERED=1

networks:
  simurf_net:
    driver: bridge